spring:
  application:
    name: electronics-store
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/electronics-store
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
